services:
  hugot:
    image: hugot:dev
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
      target: hugot-runtime
    volumes:
      - /home/azureuser/summer_2025:/home/testuser/repositories
    entrypoint: ["tail", "-f", "/dev/null"]
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]
